name: "Hand Gesture Recognition"
version: "1.1.9"
image: "ghcr.io/razormeister/handgesturerecognition"
slug: "hand-gesture-recognition"
description: "Recognize hand gestures using MediaPipe and publish them to MQTT."
url: "https://github.com/potrgani/hand-gesture-recognition-ha-addon/tree/main"
startup: application
boot: auto
host_network: true  # Use host network mode
ingress_panel: true
docker:
  image: your-addon-image:latest
  privileged: true
  ports:
    - "1883:1883"
  restart: always
  network_mode: host  # Use host network mode
init: false
arch:
  - aarch64
map:
  - config:rw
  - ssl

options:
  rtsp_url: rtsp://192.168.5.3:8554/camera  
  mqtt_host: 192.168.5.3
  mqtt_port: 1883
  mqtt_username: razor
  mqtt_password: null
  mqtt_topic: "hand_gesture_status"
  mqtt_enable_topic: "hand_gesture_enable"
  reset_hand_status_time: 10
  analyze_interval: 0.4
  num_hands: 4
  min_hand_detection_confidence: 0.3
  min_hand_presence_confidence: 0.5
  min_tracking_confidence: 0.5
  min_gesture_score: 0.5
  roi_top: 0.5
  roi_bottom: 1.0
  roi_left: 0.0
  roi_right: 1.0

schema:
  rtsp_url: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
  mqtt_topic: str
  mqtt_enable_topic: str
  reset_hand_status_time: int
  analyze_interval: float
  num_hands: int
  min_hand_detection_confidence: float
  min_hand_presence_confidence: float
  min_tracking_confidence: float
  min_gesture_score: float
  roi_top: float
  roi_bottom: float
  roi_left: float
  roi_right: float
